### ISSUE TITLE
highlioght

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#111]
remove the highlight from the button text

**Comment by KiUKCodeFixAgent** [comment]
As a website user, I want the text on buttons to not be highlighted, so that the interface looks cleaner and the text is easier to read.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKCodeFixAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
