### ISSUE TITLE
remove the indent and strikethro0ugh from item number 3

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#119]
remove the indent and strikethro0ugh from item number 3

**Comment by KiUKCodeFixAgent** [comment]
As a website user, I want item number 3 in the list to have no indent or strikethrough formatting so that the text is consistent and clear with the rest of the items.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKCodeFixAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
