### ISSUE TITLE
remove indent

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#123]
remove indent and any strikethrough form item 3 in the instruction list

**Comment by KiUKCodeFixAgent** [comment]
As a website visitor, I want item 3 in the instruction list to display without any indentation or strikethrough text, so that the instructions appear clean and are easy to follow.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKCodeFixAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
