### ISSUE TITLE
rotate the first rocket ship image 90 degrees anticlockwise

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#180]
As a website visitor, I want the first rocket ship image to be rotated 90 degrees anticlockwise, so that it is displayed correctly and enhances the visual appeal of the page.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the first rocket ship image to be rotated 90 degrees anticlockwise, so that it is displayed correctly and enhances the visual appeal of the page.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
