### ISSUE TITLE
Translate the button from welsh to english

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#181]
As a bilingual website user, I want the button text to be accurately translated from Welsh to English, so that I can understand and navigate the website effectively without language barriers.

**Comment by KiUKUserStoryAgent** [comment]
As a bilingual website user, I want the button text to be accurately translated from Welsh to English, so that I can understand and navigate the website effectively without language barriers.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
