### ISSUE TITLE
remove the indentation from the third item in the instruction list

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#182]

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the indentation of the third item in the instruction list to be consistent with the other items, so that the list appears neatly formatted and easy to read.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
4 code fixes have already been requested or the game is over.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
