### ISSUE TITLE
rotate the bottom left rocket ship image 90 degrees clockwise

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#191]
As a website user, I want the bottom left rocket ship image to be rotated 90 degrees clockwise, so that it aligns correctly with the website's layout and visual design.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
