### ISSUE TITLE
translate the button text from welsh to english 

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#192]
As a website user, I want the button text to be translated from Welsh to English, so that I can understand the functionalities and navigate the site effectively.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the button text to be translated from Welsh to English, so that I can understand the functionalities and navigate the site effectively.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
