### ISSUE TITLE
remove the indent on the third item in the instruction list

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#194]
As a website user, I want the third item in the instruction list to align with the other items, so that the list has a uniform appearance and is easier to read.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the third item in the instruction list to align with the other items, so that the list has a uniform appearance and is easier to read.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
