### ISSUE TITLE
remove the indent in the third item on the instructions list

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#199]
As a website user, I want the third item on the instructions list to align with the rest of the items, so that the text presentation is uniform and easy to follow.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the third item on the instructions list to align with the rest of the items, so that the text presentation is uniform and easy to follow.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
