### ISSUE TITLE
remove the indentation from the third item in the instructions list

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#213]

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the indentation of the third item in the instructions list to be consistent with the other items, so that the list appears orderly and easy to read.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
4 code fixes have already been requested or the game is over.

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
