### ISSUE TITLE
The 6th instruction has a strikethrough, this should be removed

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#217]
As a website user, I want the 6th instruction on the webpage to be clearly readable without any strikethrough formatting, so that I can easily understand and follow the instructions provided.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the 6th instruction on the webpage to be clearly readable without any strikethrough formatting, so that I can easily understand and follow the instructions provided.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.
