### ISSUE TITLE
The 6th instruction has a strikethrough it, which needs to be removed

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#219]
As a website user, I want the 6th instruction in the instruction box to be clear and without any strikethrough formatting so that I can easily understand and follow the steps provided.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the 6th instruction on the instruction page to be clear and without any strikethrough formatting so that I can easily understand and follow the steps provided.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
It is the instruction box not page

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the 6th instruction in the instruction box to be clear and without any strikethrough formatting so that I can easily understand and follow the steps provided.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.
