### ISSUE TITLE
The 6th instruction has a strikethrough, which needs to be removed

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#222]
As a website user, I want the strikethrough removed from the 6th instruction on the instruction page, so that the text is clear and readable without any formatting errors.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the strikethrough removed from the 6th instruction on the instruction page, so that the text is clear and readable without any formatting errors.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
