### ISSUE TITLE
in the css rotate the bottom left rocket ship image 90 degrees clockwise

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#246]
As a website visitor, I want the bottom left rocket ship image to be rotated 90 degrees clockwise so that it aligns properly with the design and orientation of other elements on the page.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the bottom left rocket ship image to be rotated 90 degrees clockwise so that it aligns properly with the design and orientation of other elements on the page.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
