### ISSUE TITLE
rotate the rocket ship image 90 degrees clockwise

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#273]

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the rocket ship image rotated 90 degrees clockwise, so that it appears upright and visually correct on the page.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
