### ISSUE TITLE
make the temperature button the same colour as the other buttons

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#285]
As a website user, I want the temperature button to have the same color as the other buttons so that the interface looks consistent and visually harmonious.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the temperature button to have the same color as the other buttons so that the interface looks consistent and visually harmonious.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
