### ISSUE TITLE
remove the indentation from the third item in the instructions list

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#286]
As a website user, I want the indentation removed from the third item in the instructions list, so that the format is consistent and easy to follow.

**Comment by kanishk-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
