### ISSUE TITLE
rotate the bottom left rocket ship image 90 degrees clockwise

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#290]
As a website visitor, I want the bottom left rocket ship image to be rotated 90 degrees clockwise, so that it aligns correctly with other content and enhances the visual appeal of the page.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the bottom left rocket ship image to be rotated 90 degrees clockwise, so that it aligns correctly with other content and enhances the visual appeal of the page.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix
