### ISSUE TITLE
make the background green

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#299]

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the background color to be green, so that the website has a more visually appealing and calming appearance.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
4 code fixes have already been requested or the game is over.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
