### ISSUE TITLE
in instruction 3rd instruction, remove tab

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#354]
As a website user, I want the third instruction on the web page to be correctly formatted by removing any unnecessary tab space, so that the instructions appear clear and easy to follow.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the third instruction on the web page to be correctly formatted by removing any unnecessary tab space, so that the instructions appear clear and easy to follow.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
