### ISSUE TITLE
the radio button needs to be translated from welsh into british english

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#369]
As a bilingual website user, I want the radio buttons to be accurately translated from Welsh into British English, so that I can understand and select options confidently and accurately.

**Comment by KiUKUserStoryAgent** [comment]
As a bilingual website user, I want the radio buttons to be accurately translated from Welsh into British English, so that I can understand and select options confidently and accurately.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
