### ISSUE TITLE
The instructions button needs to be translated into english

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#388]

**Comment by KiUKUserStoryAgent** [comment]
As a non-native speaker, I want the instructions button to be translated into English, so that I can easily understand how to navigate and use the website.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
4 code fixes have already been requested or the game is over.

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
