### ISSUE TITLE
The background should be orange

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#398]
As a user, I want the background of the website to be orange, so that it aligns with the site’s design theme and enhances the overall user experience.

**Comment by KiUKUserStoryAgent** [comment]
As a user, I want the background of the website to be orange, so that it aligns with the site’s design theme and enhances the overall user experience.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Waiting for one or more previous fixes to be merged before attempting this fix

**Comment by KiUKCodeFixAgent** [comment]
4 code fixes have already been requested or the game is over.
