### ISSUE TITLE
the temperature button is pink but it should be the same colour as the others

### ISSUE THREAD

**Issue by Ki-Spaceship-Captain** [Ki-Reply-Uk/xchange24-game#400]
As a website user, I want the temperature button to match the color scheme of the other buttons, so that the website has a consistent and professional look.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the temperature button to match the color scheme of the other buttons, so that the website has a consistent and professional look.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by Ki-Spaceship-Captain** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKCodeFixAgent** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
