### ISSUE TITLE
the temperature button is pink but should be the same as the rest of the colours

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#412]
As a website user, I want the temperature button to be the same color as the rest of the buttons, so that it maintains a consistent and cohesive design aesthetic.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the temperature button to be the same color as the rest of the buttons, so that it maintains a consistent and cohesive design aesthetic.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by Ki-Spaceship-Captain** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
