### ISSUE TITLE
in the instrudtions text, the third bullet point is on the right when it should be aligned to the left

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#413]
As a website visitor, I want the instructions text to be visually consistent, specifically aligning the third bullet point to the left, so that it is easier to read and follow the content accurately.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the instructions text to be visually consistent, so that it is easier to read and follow the content accurately.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
you need to specify that the 3rd bullet should be aligned left

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the instructions text to be visually consistent, specifically aligning the third bullet point to the left, so that it is easier to read and follow the content accurately.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by Ki-Spaceship-Captain** [comment]
Code Fix agent was unable to perform the fixes. Please re-create the issue with more detail.
