### ISSUE TITLE
the bottom left orocket needs to be rotated 90 degrees to allign the picture together #415

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#416]
As a website user, I want the bottom left rocket image to be rotated 90 degrees so that it aligns with the rest of the pictures on the page, in order to create a cohesive and visually pleasing layout.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the bottom left rocket image to be rotated 90 degrees so that it aligns with the rest of the pictures on the page, in order to create a cohesive and visually pleasing layout.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.
