### ISSUE TITLE
the bottom left orocket needs to be rotated 90 degrees to allign the picture together 

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#417]
As a website visitor, I want the bottom left rocket to be rotated 90 degrees, so that the pictures align correctly and create a cohesive visual presentation on the website.

**Comment by KiUKUserStoryAgent** [comment]
As a website visitor, I want the bottom left rocket to be rotated 90 degrees, so that the pictures align correctly and create a cohesive visual presentation on the website.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.
