### ISSUE TITLE
make the background red

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-game#57]
make the background red

**Comment by kicodedev2** [comment]
As a website user, I want the background color to be changed to red, so that it matches the theme and aesthetics of the website.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by kicodedev2** [comment]
User story acknowledged. Code fix agent executing fix based on this user story...
