### ISSUE TITLE
Testing new assignee

### ISSUE THREAD

**Issue by sonanuga-reply** [Ki-Reply-Uk/xchange24-game#93]
I want to change the background colour to black

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the option to change the background color to black, so that I can enjoy a darker theme, which is easier on my eyes and conserves battery life on my devices.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by sonanuga-reply** [comment]
Yes

**Comment by KiUKUserStoryAgent** [comment]
User story acknowledged.

**Comment by KiUKUserStoryAgent** [comment]
As a user, I want the ability to change the background color to black, so that I can have a darker theme which is easier on my eyes and potentially saves battery life on my device.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by KiUKUserStoryAgent** [comment]
As a website user, I want the option to change the background color to black, so that I can have a visually comfortable experience, especially in low-light conditions.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.
